parameters:
  project: ''
  test: true

jobs:
- template: /src/build/npm/jobs/npm-package.job.yaml@templates
  parameters:
    path: projects/audacia/${{parameters.project}}
    test: ${{parameters.test}}
    displayName: Build
