parameters:
  project: ''
  test: true

jobs:
- deployment: Deploy
  displayName: Deploy
  environment: NPM Internal
  strategy:
    runOnce:
      deploy:
        steps:

        - task: npmAuthenticate@0
          displayName: Authenticate
          inputs:
            workingFile: $(Pipeline.Workspace)/$(Build.DefinitionName)/.npmrc

        - task: UpdateNpmVersions@1
          displayName: NPM Versioning
          inputs:
            workingDirectory: $(Pipeline.Workspace)/$(Build.DefinitionName)

        - task: Npm@1
          displayName: Publish
          inputs:
            command: publish
            workingDir: $(Pipeline.Workspace)/$(Build.DefinitionName)
            verbose: false
            publishRegistry: useFeed
            publishFeed: 'Audacia.Public/AudaciaPublic'
            publishPackageMetadata: true
