parameters:
  project: ''
  test: true

jobs:
- deployment: Deploy
  displayName: Deploy
  environment: NPM Internal
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  strategy:
    runOnce:
      deploy:
        steps:

        - task: npmAuthenticate@0
          displayName: Authenticate
          inputs:
            workingFile: $(Pipeline.Workspace)/$(Build.DefinitionName)/.npmrc

        - task: AudaciaNpmVersioning@0
          displayName: Version
          inputs:
            packageJsonLocation: $(Pipeline.Workspace)/$(Build.DefinitionName)
            packageName: '@audacia/${{parameters.project}}'

        - task: Npm@1
          displayName: Publish
          inputs:
            command: publish
            workingDir: $(Pipeline.Workspace)/$(Build.DefinitionName)
            verbose: false
            publishRegistry: useFeed
            publishFeed: f09ace73-ace9-4751-ab42-2fada3f24d78
