name: $(Build.BuildId).$(Year:yy)$(DayOfYear)
resources: { repositories: [ { repository: templates, type: git, name: Audacia/Audacia.Build.Templates } ] }
trigger: { branches: { include: [ master ] }, paths: { include: [ /projects/audacia/base-url-interceptor ] } }

stages:

- stage: Build
  displayName: Build
  jobs:

  - template: /build.template.yaml
    parameters:
      project: base-url-interceptor
      test: false

- stage: Release
  displayName: Release
  jobs:

  - template: /release.template.yaml
    parameters:
      project: base-url-interceptor
      test: false

