name: $(Build.BuildId).$(Year:yy)$(DayOfYear)
resources: { repositories: [ { repository: templates, type: git, name: Audacia/Audacia.Build.Templates } ] }
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - /projects/audacia/base-url-interceptor

steps:

- template: /steps/npm/authenticate.yaml@templates
  parameters:
    project: projects/audacia/base-url-interceptor

- task: Npm@1
  displayName: Install
  inputs:
    command: custom
    workingDir: $(Build.SourcesDirectory)
    verbose: false
    customCommand: 'ci'

- task: Npm@1
  displayName: Build
  inputs:
    command: custom
    workingDir: projects/audacia/base-url-interceptor
    verbose: false
    customCommand: 'run ng -- build'

- template: /steps/npm/test.yaml@templates
  parameters:
    project: projects/audacia/base-url-interceptor
    test: false

- template: /steps/npm/publish.yaml@templates
  parameters:
    project: projects/audacia/base-url-interceptor
