name: $(Year:yy)$(DayOfYear).$(Rev:r)
trigger: { branches: { include: [ master ] }, paths: { include: [ /projects/audacia/date-parse-interceptor ] } }
pr: { branches: { include: [master] } }
resources: { repositories: [ { repository: templates, type: git, name: Audacia/Audacia.Build } ] }
pool: { name: Prometheus }

stages:

- stage: Build
  displayName: Build
  jobs:

    - template: /build.template.yaml
      parameters:
        project: date-parse-interceptor
        test: false

- stage: Release
  displayName: Release
  condition: and(succeeded(), and(not(eq(variables['Build.Reason'], 'PullRequest')), not(eq(variables['Build.Reason'], 'Schedule'))))

  jobs:

    - template: /release.template.yaml
      parameters:
        project: date-parse-interceptor
        test: false
