name: $(Build.BuildId).$(Year:yy)$(DayOfYear)
trigger: { branches: { include: [ master ] }, paths: { include: [ /projects/audacia/date-parse-interceptor ] } }
pr: { branches: { include: [master] } }
schedules: [ { cron: "0 0 * * *", displayName: Nightly Build, branches: { include: [ master ] } } ]
resources: { repositories: [ { repository: templates, type: git, name: Audacia/Audacia.Build } ] }

jobs:

- template: /build.template.yaml
  parameters:
    project: date-parse-interceptor
    test: false
