name: $(Build.BuildId).$(Year:yy)$(DayOfYear)
trigger: { branches: { include: [ master ] }, paths: { include: [ /projects/audacia/response-interceptor ] } }
pr: { branches: { include: [master] } }
schedules: [ { cron: "0 0 * * *", displayName: Nightly Build, branches: { include: [ master ] } } ]
resources: { repositories: [ { repository: templates, type: git, name: Audacia/Audacia.Build } ] }

stages:

- stage: Build
  displayName: Build
  jobs:

    - template: /build.template.yaml
      parameters:
        project: response-interceptor
        test: false

- stage: Release
  displayName: Release
  condition: and(succeeded(), and(not(eq(variables['Build.Reason'], 'PullRequest')), not(eq(variables['Build.Reason'], 'Schedule'))))
  jobs:

    - template: /release.template.yaml
      parameters:
        project: response-interceptor
        test: false
